# TimeMosaic FusionV2 — ECL (Electricity) 96/320
# Key V2 improvements over V1:
#   + DRoPE (instance-wise rotary position embedding) replaces static PE
#   + MoE learnable bias replaces lam_moe / lam_prefix_moe
#   + Log-decay loss weights on forecast
model_name=TimeMosaic_FusionV2

# ===== seq_len=96 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_96 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 256 \
  --d_ff 512 \
  --learning_rate 0.001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_192 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_336 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_96_720 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

# ===== seq_len=320 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_320_96 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_320_192 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_320_336 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --gpu 0 \
  --root_path ./dataset/electricity/ \
  --data_path electricity.csv \
  --model_id ECL_320_720 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 321 \
  --dec_in 321 \
  --c_out 321 \
  --des 'Exp' \
  --n_heads 2 \
  --d_model 128 \
  --d_ff 256 \
  --learning_rate 0.0001 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --batch_size 16 \
  --patience 3 \
  --train_epochs 10 \
  --itr 1
