# TimeMosaic FusionV2 — ETTm2
model_name=TimeMosaic_FusionV2

# ===== seq_len=96 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_96 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_192 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_336 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_720 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

# ===== seq_len=320 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_96 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_192 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_336 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_720 \
  --model TimeMosaic_FusionV2 \
  --data ETTm2 \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1
