# TimeMosaic FusionV2 — Exchange Rate
model_name=TimeMosaic_FusionV2

# ===== seq_len=96 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_192 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 1 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_336 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 16 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_720 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 2 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

# ===== seq_len=320 =====

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_96 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 16 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_192 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 1 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_336 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 4 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_720 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 2 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --des 'Exp' \
  --itr 1
