# TimeMosaic FusionV2 — Weather
model_name=TimeMosaic_FusionV2

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_96 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 1 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --train_epochs 10

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_192 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 4 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --train_epochs 10

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_336 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --train_epochs 10

python -u run.py \
  --task_name Exp_FusionV2 \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_720 \
  --model TimeMosaic_FusionV2 \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 8 \
  --moe_bias_rate 0.001 \
  --prefix_len 4 \
  --freq_num 4 \
  --use_drope 1 \
  --use_log_decay 1 \
  --result_file "result_FusionV2.txt" \
  --train_epochs 10
