model_name=TimeMosaic_Fusion

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_96 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 3 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_192 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 1 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_336 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 16 \
  --num_moe_experts 7 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 4 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_96_720 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_96 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 7 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_192 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 1 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_336 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 16 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTm2.csv \
  --model_id ETTm2_320_720 \
  --model TimeMosaic_Fusion \
  --data ETTm2 \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --itr 1
