model_name=TimeMosaic_Fusion

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03 \
  --model TimeMosaic_Fusion \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --channel CD \
  --pred_len 12 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 128 \
  --d_ff 256 \
  --batch_size 32 \
  --learning_rate 0.003 \
  --train_epochs 10 \
  --patience 10 \
  --use_multi_gpu \
  --devices 0,1 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS04.npz \
  --model_id PEMS04 \
  --model TimeMosaic_Fusion \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --channel CD \
  --pred_len 12 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 128 \
  --d_ff 256 \
  --batch_size 32 \
  --learning_rate 0.003 \
  --train_epochs 10 \
  --patience 10 \
  --use_multi_gpu \
  --devices 0,1 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS07.npz \
  --model_id PEMS07 \
  --model TimeMosaic_Fusion \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --channel CD \
  --pred_len 12 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 883 \
  --dec_in 883 \
  --c_out 883 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 128 \
  --d_ff 256 \
  --batch_size 32 \
  --learning_rate 0.003 \
  --train_epochs 10 \
  --patience 10 \
  --use_multi_gpu \
  --devices 0,1 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08 \
  --model TimeMosaic_Fusion \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 0 \
  --channel CD \
  --pred_len 12 \
  --e_layers 5 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 128 \
  --d_ff 256 \
  --batch_size 32 \
  --learning_rate 0.003 \
  --train_epochs 10 \
  --patience 10 \
  --use_multi_gpu \
  --devices 0,1 \
  --itr 1
