model_name=TimeMosaic_Fusion

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_96 \
  --model TimeMosaic_Fusion \
  --data Solar \
  --features M \
  --channel CD \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 2048 \
  --learning_rate 0.001 \
  --train_epochs 10 \
  --patience 3 \
  --batch_size 32 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_192 \
  --model TimeMosaic_Fusion \
  --data Solar \
  --features M \
  --channel CD \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 2048 \
  --learning_rate 0.001 \
  --train_epochs 10 \
  --patience 3 \
  --batch_size 32 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_336 \
  --model TimeMosaic_Fusion \
  --data Solar \
  --features M \
  --channel CD \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 336 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 2048 \
  --learning_rate 0.001 \
  --train_epochs 10 \
  --patience 3 \
  --batch_size 32 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_720 \
  --model TimeMosaic_Fusion \
  --data Solar \
  --features M \
  --channel CD \
  --seq_len 96 \
  --label_len 0 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 2048 \
  --learning_rate 0.001 \
  --train_epochs 10 \
  --patience 3 \
  --batch_size 32 \
  --itr 1
