model_name=TimeMosaic_Fusion

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_96 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 6 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 2 \
  --accumulation_steps 2 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_192 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 5 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_336 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_96_720 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 5 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1



python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_320_96 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 9 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 4 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_320_192 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 5 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_320_336 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 4 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/traffic/ \
  --data_path traffic.csv \
  --model_id traffic_320_720 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --channel CDP \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 862 \
  --dec_in 862 \
  --c_out 862 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 4 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --d_model 512 \
  --d_ff 512 \
  --batch_size 4 \
  --itr 1

