model_name=TimeMosaic_Fusion

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location2.csv \
  --model_id Wind2_96_96 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --freq_num 4 \
  --result_file "result_Fusion.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location2.csv \
  --model_id Wind2_96_192 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --freq_num 4 \
  --result_file "result_Fusion.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location2.csv \
  --model_id Wind2_96_336 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --freq_num 4 \
  --result_file "result_Fusion.txt" \
  --itr 1

python -u run.py \
  --task_name Exp_Fusion \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location2.csv \
  --model_id Wind2_96_720 \
  --model TimeMosaic_Fusion \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 16 \
  --num_moe_experts 4 \
  --lam_moe 0.001 \
  --num_moe_prefix_experts 2 \
  --prefix_len 4 \
  --lam_prefix_moe 0.001 \
  --freq_num 4 \
  --result_file "result_Fusion.txt" \
  --itr 1
