model_name=TimeMosaic_MoE

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_96 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 16 \
  --num_moe_experts 6 \
  --lam_moe 0.008 \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_192 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 1 \
  --num_moe_experts 9 \
  --lam_moe 0.001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_336 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 4 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_720 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 2 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --des 'Exp' \
  --itr 1
