model_name=TimeMosaic_MoE

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location4.csv \
  --model_id Wind4_320_96 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --target Power \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 2 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location4.csv \
  --model_id Wind4_320_192 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location4.csv \
  --model_id Wind4_320_336 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 8 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic_MoE \
  --is_training 1 \
  --root_path ./dataset/wind/ \
  --data_path Location4.csv \
  --model_id Wind4_320_720 \
  --model TimeMosaic_MoE \
  --data custom \
  --features M \
  --target Power \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 9 \
  --dec_in 9 \
  --c_out 9 \
  --des 'Exp' \
  --n_heads 16 \
  --num_moe_experts 8 \
  --lam_moe 0.001 \
  --itr 1
