model_name=TimeMosaic

python -u run.py \
  --task_name Exp_TimeMosaic \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_96 \
  --model TimeMosaic \
  --data custom \
  --features M \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'Exp' \
  --n_heads 16 \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_192 \
  --model TimeMosaic \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 1 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --task_name Exp_TimeMosaic \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_336 \
  --model TimeMosaic \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 1 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 4 \
  --des 'Exp' \
  --itr 1 

python -u run.py \
  --task_name Exp_TimeMosaic \
  --is_training 1 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_320_720 \
  --model TimeMosaic \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --n_heads 2 \
  --des 'Exp' \
  --codebook_size 64 \
  --lambda_vq 0.1 \
  --ema_decay 0.99 \
  --itr 1
