model_name=TimeMosaic_new

python -u run.py \
  --task_name TimeMosaic_new \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_96 \
  --model TimeMosaic_new \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 1 \
  --train_epochs 10

python -u run.py \
  --task_name TimeMosaic_new \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_192 \
  --model TimeMosaic_new \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 4 \
  --train_epochs 10

python -u run.py \
  --task_name TimeMosaic_new \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_336 \
  --model TimeMosaic_new \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 8 \
  --train_epochs 10

python -u run.py \
  --task_name TimeMosaic_new \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id weather_320_720 \
  --model TimeMosaic_new \
  --data custom \
  --features M \
  --channel CDA \
  --seq_len 320 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --itr 1 \
  --n_heads 8 \
  --train_epochs 10
